import "@/app/styles/globals.css";
import { Montserrat } from 'next/font/google';
import { Auth0Provider } from '@auth0/nextjs-auth0';

export const metadata = {
  title: "PageFolio",
  description: "Generated by create next app",
};

const montserrat = Montserrat({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Auth0Provider>
        <body className={montserrat}>
          {children}
        </body>
      </Auth0Provider>
    </html>
  );
}
