import "@/app/styles/globals.css";
import { Montserrat } from 'next/font/google'

export const metadata = {
  title: "PageFolio",
  description: "Generated by create next app",
};

const montserrat = Montserrat();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat}>
        {children}
      </body>
    </html>
  );
}
